### PR TITLE
Response with no items

### PR DESCRIPTION
**Pull request by mindflayer**
I know we can't cover all the slicing API features, but it could be very useful having a syntax to ask for 0 items.
I use it when I am only interested in aggregations, or I need to know how many items respond to my query.

### CODE REVIEW

**Comment by amitpandita** [comment]
I think the above feature is already available, provide you use the below syntax

s = Search(using=es, index=settings.ES_INDEX, doc_type="MyDoc").params(search_type="count")

just append "search_type" param to count and you will onle get the aggregations.

**Comment by mindflayer** [comment]
Am I wrong if I say that you are counting the aggregations result? I would like to obtain something similar to the following query:

```{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "customer_id": "%s"
                    }
                }
            ],
            "must_not": [],
            "should": [
                {
                    "term": {
                        "user": "%s"
                    }
                }
            ],
            "minimum_should_match": 1
        }
    },
    "from": 0,
    "size": 0,
    "sort": [],
    "aggs": {
        "games": {
            "terms": {
                "field": "content_id"
            },
            "aggs": {
                "time_spent": {
                    "sum": {
                        "field": "duration"
                    }
                }
            }
        }
    }
}```

**Comment by mindflayer** [comment]
Yes, you are definitely right. Thank you.

**Comment by HonzaKral** [comment]
Closing this since we have support for this. Thanks @amitpandita for the quick reply.

**Pull request closed without merging**
