### PR TITLE
Fix DeprecationWarning's from elasticsearch-py.

### LINKED ISSUE #1551: Getting deprecation warnings from es as they are preparing for next release
We are using the latest version(7.4.0) of elasticsearch-dsl in our python project. But we are getting deprecation warnings from es saying

_elasticsearch_dsl/index.py:279: DeprecationWarning: The 'body' parameter is deprecated for the 'create' API and will be removed in a future version. Instead use API parameters directly. See elastic/elasticsearch-py#1698 for more information
return self.get_connection(using).indices.create(_

Can you give some update about your future releases? Will this deprecation warning be gone with your upcoming release?

### PR DESCRIPTION
**Pull request by arnau126**
See https://github.com/elastic/elasticsearch-py/issues/1698 for more information.
Fixes #1551 .

### CODE REVIEW

**Review by sethmlarson — COMMENTED** [review]
Thanks for this, if we're making this change we need to make the minimum required `elasticsearch` package to be 7.14.0 as we're now using `document=` instead of `body=`.

**Comment by arnau126** [comment]
We can also do something like:
```
        if VERSION >= (7, 14, 0):
            key = 'document'
        else:
            key = 'body'
        meta = es.index(
            index=self._get_index(index),
            **{key: self.to_dict(skip_empty=skip_empty)},
            **doc_meta
        )
```

**Comment by arnau126** [comment]
@sethmlarson Please, let me know if I anything else is required.
(I've rebased the branch).

**Comment by arnau126** [comment]
@sethmlarson Please, let me know if anything else is required.
(I've rebased the branch).

**Comment by sethmlarson** [comment]
Thanks for this, I've [created a separate PR](https://github.com/elastic/elasticsearch-dsl-py/pull/1642) which fixed the deprecations for all APIs. The fix is available on v7.4.1 on PyPI.

**Pull request closed without merging**
