### PR TITLE
Fix for datetime with timzone info

### PR DESCRIPTION
**Pull request by 27tech**
Avoid microseconds issue
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-date-format.html#mapping-date-format

### CODE REVIEW

**Comment by HonzaKral** [comment]
Thanks for the PR, do you have any more information on what the issue is with microseconds?

In 3e252e2029db5453a8a9b0394a4999b5637f2435 I added microseconds to a timezone-aware datetime and it was deserialized properly.

**Comment by 27tech** [comment]
If microseconds are not equal to 0, then timezone information will be loosed in elasticsearch request deserialization, because datetime to str representation contains more microseconds digits that expected by elasticsearch deserializer.

**Comment by HonzaKral** [comment]
In 3351e0a3ddc043bce0467ae31bd932bea7a84566 I added a test for that and it seems to be working, could you please provide more details on what is exactly not working for you and how to replicate it please?

Thanks!

**Comment by 27tech** [comment]
Python default datetime string representaion is datetime.isoformat([sep])
Return a string representing the date and time in ISO 8601 format, YYYY-MM-DDTHH:MM:SS.mmmmmm or, if microsecond is 0, YYYY-MM-DDTHH:MM:SS
But elastic expects yyyy- MM-dd'T'HH:mm:ss.SSSZZ

Only 3 digits for microseconds

**Comment by HonzaKral** [comment]
Elasticsearch uses http://joda-time.sourceforge.net/api-release/org/joda/time/format/ISODateTimeFormat.html#dateOptionalTimeParser() by default where microseconds are formally defined as ```fraction          = ('.' | ',') digit+```.

Can you demonstrate how this doesn't work for you? The test I added clearly demonstrates that no precision is lost so I seem to be missing something.

Thanks!

**Comment by 27tech** [comment]
Can't reproduce issue now, may be is depends on django dataetime field. But try add test with UTC timezone

`from __future__ import absolute_import, unicode_literals
from elasticsearch_dsl import DocType, field
import pytz
import datetime

class TimeZoneTestDoc(DocType):
    created_at = field.Date()
    class Meta:
        index = 'inby_test_2'


def test_timezone(dt_with_timezone, test_num):
    print dt_with_timezone.isoformat()

    doc = TimeZoneTestDoc(
        created_at=dt_with_timezone
    )
    doc.meta.id = test_num
    doc.save()

    doc = TimeZoneTestDoc.get(id=test_num)
    print doc.created_at.isoformat()
    return dt_with_timezone == doc.created_at

def run_test():
    TimeZoneTestDoc.init()

    dt_with_timezone = pytz.timezone("UTC").localize(datetime.datetime.now())

    assert test_timezone(dt_with_timezone.replace(microsecond=0), 1)
    assert test_timezone(dt_with_timezone.replace(microsecond=88376), 2)
`

**Comment by 27tech** [comment]
Are you reproduced tzinfo loose with UTC timezone?
Let me know, seems I should find the problem with django integration. 
Thanks.

**Comment by HonzaKral** [comment]
This code works for me as well.

I am closing this issue, feel free to reopen if you manage to replicate the issue.

Thanks!

**Comment by 27tech** [comment]
Thanks

**Pull request closed without merging**
