### PR TITLE
Drop support for EOL Python 2.6, 3.2 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6, 3.2 and 3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.5 | 2006-09-19 | 2011-05-26
2.6 | 2008-10-01 | 2013-10-29
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29

Source: https://en.wikipedia.org/wiki/CPython#Version_history

They're also little used. Here's the pip installs for elasticsearch-dsl from PyPI for last month:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.5 |  90.19% | 2,874,079 |
|      2.7 |   5.85% |   186,311 |
|      3.6 |   3.01% |    95,827 |
|      3.4 |   0.54% |    17,107 |
|      3.7 |   0.33% |    10,460 |
| null     |   0.06% |     1,854 |
|      3.8 |   0.03% |       813 |
|      2.6 |   0.00% |        39 |
|      3.2 |   0.00% |        30 |
|      3.3 |   0.00% |        24 |
| Total    |         | 3,186,544 |

Source: `pypistats python_minor --last-month elasticsearch-dsl`

Also fix a couple of code inspection things, and add `python_requires` to help pip.

### CODE REVIEW

**Comment by 3lnc** [comment]
@HonzaKral can we merge this?

**Comment by HonzaKral** [comment]
Not before we cut the last `6.x` release and prepare for `7.x` at least as this is a breaking change. I aslo do not understand the need for this - right now the codebase works for all the python versions and the overhead of maintanance is not too big so what is the reason behind this request?

Any views would be welcome!

**Comment by hugovk** [comment]
Stats for February:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.5 |  76.80% | 1,349,050 |
|      2.7 |  14.25% |   250,364 |
|      3.6 |   6.91% |   121,407 |
|      3.7 |   1.15% |    20,128 |
|      3.4 |   0.72% |    12,671 |
| null     |   0.16% |     2,781 |
|      3.8 |   0.01% |       196 |
|      3.2 |   0.00% |        28 |
|      2.6 |   0.00% |        18 |
| Total    |         | 1,756,643 |

(Python 3.4 is now also EOL.)

**Comment by HonzaKral** [comment]
Merged, thank you for the patch!

**Pull request merged**
