### PR TITLE
feat: Add a `collapse` method to `elasticsearch_dsl.search.Search`

### LINKED ISSUE #1215: Add support for collapse param in Search
There's no method for collapse feature. [Collapsing feature](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/search-request-collapse.html) is vary usefull for building suggestions.

To use this feature right now in v7.0.0 of *e-dsl* I can use this workaround:
```python
s = Search(...)
s = s.update_from_dict({'collapse': {'field': 'some.field'}})
```

It'll be much easier to use it in a way like that:
```python
s = Search(...)
s = s.collapse('some.field', 'some.another.field')
s = s.collapse('some.complicated.field'={
  'inner_hits': ...,
  '...': ...
})
````

### PR DESCRIPTION
**Pull request by qcoumes**
This PR adds a `collapse` method to `elasticsearch_dsl.search.Search` which allows adding a collapse requirement to a query without the need for `.extra()` or `update_from_dict()`.

This is achieved similarly to how `sort()` is done.

Issues Resolved
#1215

### CODE REVIEW

**Comment by offensity** [comment]
when will this be merged? 
looks like the only error is that python 3.6 is not avilable on ubuntu 22.04

**Review by pquentin — CHANGES_REQUESTED** [review]
Thanks!

You're missing `s._collapse = self._collapse.copy()` in `_clone()`. This was not visible in the unit test because `.collapse()` was the last method you called. The following search made this bug visible:

```python3
s = (
    Search()
    .query("match", message="GET /search")
    .collapse(field="user_id.keyword")
    .sort("-bytes")
)
```

Can you please adjust `test_collapse` to do something similar?

**Comment by pquentin** [comment]
@qcoumes Is this something you want to tackle or should I go ahead and do it myself?

**Comment by qcoumes** [comment]
Sorry, I did not see the notification. You can take over the PR if you want, I don't have the time to work on it right now.

**Review by pquentin — APPROVED** [review]

**Pull request merged**
