### PR TITLE
Populate document.save/update result value

### PR DESCRIPTION
**Pull request by amih90**
I found very useful the return value of the persistence methods, but they are populated in a none standard way (with a boolean) in case of `save` and doesn't populated at all when update.

### CODE REVIEW

**Comment by amih90** [comment]
@karmi added. is that okay now?

**Comment by karmi** [comment]
@amih90, great, the check is green now!

**Comment by amih90** [comment]
@HonzaKral Please consider merging it into the next release

**Comment by HonzaKral** [comment]
@amih90 I am planning to merge this for `7.0` since it is a backwards incompatible change, thank you for the patch, I think it adds clarity to the confusion that was the boolean value :)

**Comment by HonzaKral** [comment]
Merged as e3d4336

Thank you for the patch!

**Pull request closed without merging**
