### PR TITLE
Move default value of 'expand__to_dot' to a variable (#499)

### PR DESCRIPTION
**Pull request by TheName**
Can we please add it to branch 2.x as well?

### CODE REVIEW

**Comment by 3lnc** [comment]
Hi.

Can you pls describe the reason behind this change?

**Comment by TheName** [comment]
I see no way of replying to you other than mail; I don't see that question
in the thread, I hope it's OK.

The reason is simple: in the project where I'm using your library, most of
the fields have double underscore in their names, so I'd have to pass that
argument every time I create a query which is troublesome.
This change is bacward-compatible and will make my life easier.

Cheers,
Dawid

2018-01-09 20:35 GMT+01:00 Slam <notifications@github.com>:

**Comment by 3lnc** [comment]
Yeah. Got it, removed comment in GH as found hypothetical usage for this.
Thx for reply.

**Comment by TheName** [comment]
@3lnc could you merge it then? :)

**Comment by 3lnc** [comment]
Nope, I have no such permissions on this repo, we need to wait for @HonzaKral

**Comment by TheName** [comment]
@HonzaKral  could you merge this PR, please?

**Comment by HonzaKral** [comment]
@TheName merged, hope it helps!

**Comment by TheName** [comment]
@HonzaKral thank you! :)

**Comment by TheName** [comment]
@HonzaKral one more question: Is pypi package v2 going to be updated to the newest code version sometime soon? I was hoping so, that's why it was important for me to merge this code change :)

**Pull request merged**
