### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pichouk**

### CODE REVIEW

**Comment by pichouk** [comment]
Just signed the CLA

**Comment by HonzaKral** [comment]
Thank you for the patch, however the typo is in the code on purpose as it showcases how you can use the `term` suggester for spell checking.

**Comment by pichouk** [comment]
I didn't check the context, sorry for the noise.

**Comment by HonzaKral** [comment]
@pichouk no worries at all, I really appreciate the effort! I added a comment to that line in e1b4653059debc6edade4e1003d1bb632fd2f688 to make it clearer what we are trying to do there.

Thanks again for taking the time to contribute

**Pull request closed without merging**
