### PR TITLE
Allow Request.index() to receive a list or tuple

### PR DESCRIPTION
**Pull request by f-santos**
Allow index to be updated with a list like when creating the Search object.

### CODE REVIEW

**Comment by HonzaKral** [comment]
Hi, when you create a `Search` object you can pass in a list even now, this PR breaks existing code.

Can you specify when this would be used? Why couldn't the users just specify `s.index(*my_list)` instead?

Thank you!

**Comment by f-santos** [comment]
Hi, didn't intend to break the current input, overlooked the single string case. Fixed it and added some tests.
The idea is to allow the same type of input as in the `Search` object argument, looks easier to handle it in the library and standardize both methods for specifying the indexes.

Thanks.

**Comment by fxdgear** [comment]
@HonzaKral ping

**Comment by HonzaKral** [comment]
Thank you fo rthe patch @f-santos !

**Pull request merged**
