### PR TITLE
Add CombinedFields query

### LINKED ISSUE #1556: Add support for "combined_fields" query
Dear team,

could you please consider adding support to the "combind_fields" query? I could see a similar request is raised in #1512, and a PR #1534  for adding the functionality is still open.

Thanks in advance!

### PR DESCRIPTION
**Pull request by Telomeraz**
Closes #1556

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]
Thanks for this! Can you sign the CLA?

**Comment by sethmlarson** [comment]
@Telomeraz Awesome, it just hadn't refreshed on the commit status. Thanks!

**Comment by lukejs97** [comment]
Am I correct that this change does not exist in the latest release? Looks like this was merged to `master` on 1/19/22 but the the last release was on 7/15/21. If so, is there a way to use `combined_fields` before the next release?

**Comment by vipulg13** [comment]
that's true! it seems that the intermediate release has been deleted.
I had this feature after upgrading the package sometime in January. Today, I accidentally upgraded the package and found that the feature is no more supported. @sethmlarson @Telomeraz could you please look into this issue?

**Comment by vipulg13** [comment]
I happened to check my old installation script and found that I installed this package via git with the then current master branch. Probably, there is no official release after v7.4.0.

**Pull request merged**
