### PR TITLE
Added 'aliases' support to Index

### PR DESCRIPTION
**Pull request by lolletsoc**
@HonzaKral, this PR adds aliases support to indexes. I wanted to add an alias at creation time and not have to do a separate call.

I didn't add a test, would you like me to?

### CODE REVIEW

**Comment by HonzaKral** [comment]
Thanks for the PR, tests would be amazing, but if you don't feel like writing them I am happy to do it.

**Comment by lolletsoc** [comment]
You're welcome! I'll write a couple of tests

**Comment by lolletsoc** [comment]
@HonzaKral Tests added

**Comment by HonzaKral** [comment]
Merged as d2ddfa66cf527769754c5b3ed3516b7e3c0100e0

Thanks!

**Pull request closed without merging**
