### PR TITLE
Accept Terms value to be any iterable

### PR DESCRIPTION
**Pull request by roxanebellot**
Fixes https://github.com/elastic/elasticsearch-dsl-py/issues/1641

CLA is signed, PR is rebased !

### CODE REVIEW

**Review by miguelgrinberg — APPROVED** [review]
Thanks!

**Comment by pquentin** [comment]
Thank you for your persistence Roxane!

**Comment by abrin** [comment]
fyi -- the way this is implemented a term of "test" will turn into a query for `['t","e","s","t"]`. not sure if this is intended, but it caught me by surprise

**Comment by pquentin** [comment]
@abrin Good news! This was fixed in https://github.com/elastic/elasticsearch-dsl-py/releases/tag/v8.15.3, released one hour ago.

**Pull request merged**
