### PR TITLE
Add support for geotile_grid agg

### PR DESCRIPTION
**Pull request by owrcasstevens**
Fixes:  https://github.com/elastic/elasticsearch-dsl-py/issues/1349

### CODE REVIEW

**Comment by sethmlarson** [comment]
Thanks, can you add a unit test for this change? You'll also need to sign the contributor agreement.

**Comment by owrcasstevens** [comment]
@sethmlarson 
Completed the contributor agreement.

**Comment by owrcasstevens** [comment]
@sethmlarson 
Once this is merged, how long before it will be included in a release?

**Comment by sethmlarson** [comment]
@owrcasstevens It's been a while since last release so I think I can release right after.

**Comment by owrcasstevens** [comment]
@sethmlarson Awesome!  Thanks!

**Comment by sethmlarson** [comment]
@owrcasstevens Released in v7.2.0

**Pull request merged**
