### PR TITLE
Add support for Wildcard type

### PR DESCRIPTION
**Pull request by algorri94**
Solves #1488

### CODE REVIEW

**Comment by algorri94** [comment]
solves #1488

**Comment by shaibrown5** [comment]
@algorri94[algorri94](https://github.com/algorri94) any chance you can you can sign the agreement to merge? 
if not I don't mind opening a new pr

**Comment by algorri94** [comment]
> @[algorri94](https://github.com/algorri94) any chance you can you can sign the agreement to merge? if not I don't mind opening a new pr. please let me know

I already signed it, but it seems it's not triggering the build again

**Comment by pquentin** [comment]
@algorri94 Sorry for the huge delay. You signed the CLA using your personal email, but the commit was made with your TrustYou email.

**Comment by miguelgrinberg** [comment]
Closing, since we cannot merge without a signed CLA.

**Comment by minaton-ru** [comment]
@miguelgrinberg 
Hello! Please tell me is it ok if I make again such pull request with supporting for Wildcard type? It seems that there is no wildcard type field in Elasticsearch-dsl till now.

**Comment by miguelgrinberg** [comment]
@minaton-ru The `Wildcard` type is coming with release 8.18, currently planned for early April. Note that starting with 8.18 this library will be merged with the regular Python client, so the 8.18 code is in https://github.com/elastic/elasticsearch-py. You can take a look at the `Wildcard` field [here](https://github.com/elastic/elasticsearch-py/blob/8dd1fb66283fee45e9b50af7ac82947e35be8e89/elasticsearch/dsl/field.py#L4136).

**Pull request closed without merging**
