### PR TITLE
Fix retry_on_conflict raising errors on document update

### PR DESCRIPTION
**Pull request by armando1793**
Closes https://github.com/elastic/elasticsearch-dsl-py/issues/1432
Closes https://github.com/elastic/elasticsearch-dsl-py/issues/1316

### CODE REVIEW

**Comment by armando1793** [comment]
> x Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [b99fa9c](https://github.com/elastic/elasticsearch-dsl-py/commit/b99fa9cbe24755d54e1e69d007feff20fd3f3e94)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

my apologies. I thought I clicked submit but the form already timed out. I already signed the form and downloaded the finished copy. Is there a way to correct this after making the PR?

**Comment by sethmlarson** [comment]
Thanks for the PR. You're removing `version`, looking at Elasticsearch source code it looks like this error message is used when seq_no is set.

Potentially the fix should be:

```python
        # Optimistic concurrency control
        if retry_on_conflict in (None, 0) and "seq_no" in self.meta and "primary_term" in self.meta:
            doc_meta["if_seq_no"] = self.meta["seq_no"]
            doc_meta["if_primary_term"] = self.meta["primary_term"]
```

and you'll need to update the PR with a test case as well.

**Comment by armando1793** [comment]
Hey @sethmlarson thanks for looking into my PR

The context for me is: I have two separate kafka consumers independently updating the same document. There's a race condition that happens where both consumers get the same document version and update it. When it happens I get the following

```
WARNING:elasticsearch:POST http://es-url:9200/index_name_v13/index/0000001243/_update?refresh=wait_for&retry_on_conflict=5&version=2 [status:400 request:0.003s]
{"message": "RequestError(400, 'action_request_validation_exception', \"Validation Failed: 1: can't provide both retry_on_conflict and a specific version;\")"}
```

From the request params and the error message I made a guess that it was because version was in the query the params. So when I override the version by doing the following on my own code, version disappears and the request pushes through

```
object.meta["version"] = None
```

```
INFO:elasticsearch:POST http://es-url:9200/index_name_v13/index/0000001258/_update?refresh=wait_for&retry_on_conflict=5 [status:200 request:0.669s]
{"message": "POS http://es-url:9200/index_name_v13/index/0000001258/_update?refresh=wait_for&retry_on_conflict=5 [status:200 request:0.669s]"}
```

I don't think changing the `if_` meta fields fixes my particular issue. Please let me know what you think!

**Comment by sethmlarson** [comment]
CLA is still falling, did you sign with the same email address attached to your commits? If not it won't go to green.

**Comment by sethmlarson** [comment]
Also if you're interested in fixing 6.x you could open a PR against 6.x :)

**Comment by armando1793** [comment]
hey @sethmlarson yeah I'm going to fix that. I misunderstood the contribution doc

Yes I am interested in working on a fix for 6.x. I'll try to get on that when I can

**Review by sethmlarson — APPROVED** [review]
LGTM, thanks so much for this! I added an extra test case for `retry_on_conflict=0` or `None`

**Comment by armando1793** [comment]
thank you, too, @sethmlarson  it was a great learning experience. btw I'm not sure where the best place is to ask this: how do I make a bug fix for 6.x? I don't see a 6.x branch in this repo

**Comment by sethmlarson** [comment]
Okay I pushed a `6.x` branch on where the last 6.x release was plus removing support for long-EOL Python versions, now you can create PRs against it :)

**Pull request merged**
