### PR TITLE
Fix broken sentence in search_dsl docs.

### PR DESCRIPTION
**Pull request by bonniejools**

### CODE REVIEW

**Comment by bonniejools** [comment]
As a side note: how do you feel about these kind of v. small changes? I was almost not going to bother.

**Comment by HonzaKral** [comment]
I am a big fan of any PRs that fix documentation, no matter how small. Thank you for those and please, keep them coming.

Could I ask you to also sign our CLA (https://www.elastic.co/contributor-agreement/), so that I can merge it? Thanks!

**Comment by bonniejools** [comment]
Just signed it.

**Comment by HonzaKral** [comment]
Merged as a88bef583c3a83c49e9e3893c6ab92a52c983afb

Thanks again!

**Pull request closed without merging**
